# Generated by Django 5.2 on 2025-05-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
